spring:
  application:
    name: travel-manager-api
  datasource:
    url: jdbc:h2:mem:traveldb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
  h2:
    console:
      enabled: true
server:
  port: 8080
